on:
  workflow_call:

jobs:
  ci-build:
    name: "ğŸ—ï¸"
    uses: ./.github/workflows/ci-01-build.yml

  ci-release:
    needs:
      - ci-build
    name: "âœï¸"
    uses: ./.github/workflows/ci-02-release.yml
